### PR TITLE
adding ros-geographic-info logo to orgunits

### PR DESCRIPTION
**Pull request by SteveMacenski**
@tfoote 

Discussion from here: https://discourse.ros.org/t/claiming-maintainership-for-geographic-info-in-ros2/10620/14

I suppose this PR is also a little bit of "any objections to making this official?" On merge, I'll change the org's image to this

### CODE REVIEW

**Comment by SteveMacenski** [comment]
I have a vector version that I can modify at a later date but to be honest, I'm not a good graphic designer so its not in a state which I think its "sharable" beyond limited access for those with _low_ expectations

**Comment by tfoote** [comment]
Ok, this is at least high enough resolution for anyone who wants to do a presentation etc.

**Comment by SteveMacenski** [comment]
I can also make this as high resolution as you want if you want more. The raw file is just a mess with like 9 layers and stuff off-page

**Comment by tfoote** [comment]
That would probably be easier for people to pick up and use rather than. There's always space for improvement, just like code. It's fine to add it in your current state.

**Pull request merged**
